import { CheckCircle2, CircleAlert, Compass, Target, TrendingUp, UserRound } from 'lucide-react'

const skills = [
  { name: 'Python', value: 82, tone: 'bg-emerald-500' },
  { name: 'SQL', value: 76, tone: 'bg-emerald-500' },
  { name: 'Statistics', value: 61, tone: 'bg-amber-400' },
  { name: 'Machine Learning', value: 42, tone: 'bg-rose-400' },
  { name: 'Power BI', value: 68, tone: 'bg-blue-500' },
]

function ScoreCard({ icon: Icon, label, value, note, tone }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className={`inline-flex rounded-xl p-2.5 ${tone}`}><Icon size={18} /></span><p className="mt-4 text-3xl font-extrabold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-sm font-bold text-slate-700">{label}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div>
}

function EmployeeCompetencyPage() {
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div className="flex items-start gap-4"><div className="grid size-14 shrink-0 place-items-center rounded-2xl bg-slate-900 text-lg font-black text-white">RS</div><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-600">My Competency</p><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-700">EMP001</span></div><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">My Competency</h2><p className="mt-1 text-sm font-medium text-slate-500">Rahul Sharma <span className="mx-1 text-slate-300">/</span> Junior Data Analyst</p><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">Understand how your current capabilities map to your target role and where to improve next.</p></div></div><div className="flex items-center gap-2 rounded-xl border border-blue-100 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700"><span className="size-2 rounded-full bg-blue-500" />Personal competency profile</div></div></section>
    <div className="grid gap-4 sm:grid-cols-2"><ScoreCard icon={Target} label="Overall Competency" value="66%" note="Across your active skills" tone="bg-emerald-50 text-emerald-600" /><ScoreCard icon={TrendingUp} label="Role Readiness" value="72%" note="Junior Data Analyst target" tone="bg-blue-50 text-blue-600" /></div>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-600">My competency profile</p><h2 className="mt-1 text-lg font-extrabold text-slate-950">Skill levels</h2><p className="mt-1 text-xs text-slate-500">Your current proficiency across the capabilities used in your target role.</p></div><UserRound size={18} className="text-slate-400" /></div><div className="mt-6 space-y-5">{skills.map((skill) => <div key={skill.name}><div className="mb-1.5 flex items-center justify-between text-sm"><span className="font-bold text-slate-700">{skill.name}</span><span className={`font-extrabold ${skill.value >= 70 ? 'text-emerald-600' : skill.value >= 55 ? 'text-amber-600' : 'text-rose-600'}`}>{skill.value}</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${skill.tone}`} style={{ width: `${skill.value}%` }} /></div></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><Compass size={18} className="text-blue-600" /><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-blue-600">Target role</p><h2 className="mt-1 text-lg font-extrabold text-slate-950">Role readiness</h2></div></div><div className="mt-6 rounded-2xl bg-slate-900 p-5 text-white"><p className="text-xs font-semibold text-slate-400">Junior Data Analyst</p><p className="mt-2 text-4xl font-black">72<span className="text-xl text-emerald-400">%</span></p><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-emerald-400" /></div><p className="mt-3 text-xs leading-5 text-slate-300">You have a strong foundation. Closing the Machine Learning and Statistics gaps will improve your readiness.</p></div><div className="mt-5 flex items-center gap-2 rounded-xl bg-blue-50 p-3 text-xs font-semibold leading-5 text-blue-700"><TrendingUp size={15} className="shrink-0" />Target role readiness is based on your current skill levels and verified evidence.</div></section></div>
    <div className="grid gap-6 xl:grid-cols-3"><section className="rounded-2xl border border-emerald-100 bg-emerald-50/50 p-5 shadow-sm"><h2 className="flex items-center gap-2 text-sm font-extrabold text-emerald-800"><CheckCircle2 size={17} />Strengths</h2><p className="mt-1 text-xs text-slate-500">Capabilities already supporting your role.</p><div className="mt-4 space-y-2"><div className="rounded-xl bg-white/80 px-3 py-3 text-sm font-bold text-slate-700">Python <span className="float-right text-emerald-700">82</span></div><div className="rounded-xl bg-white/80 px-3 py-3 text-sm font-bold text-slate-700">SQL <span className="float-right text-emerald-700">76</span></div></div></section><section className="rounded-2xl border border-rose-100 bg-rose-50/50 p-5 shadow-sm"><h2 className="flex items-center gap-2 text-sm font-extrabold text-rose-800"><CircleAlert size={17} />Skill gaps</h2><p className="mt-1 text-xs text-slate-500">Priority capabilities to strengthen.</p><div className="mt-4 space-y-2"><div className="rounded-xl bg-white/80 px-3 py-3 text-sm font-bold text-slate-700">Machine Learning <span className="float-right text-rose-700">42</span></div><div className="rounded-xl bg-white/80 px-3 py-3 text-sm font-bold text-slate-700">Statistics <span className="float-right text-amber-700">61</span></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-extrabold text-slate-950">What to improve next</h2><p className="mt-1 text-xs leading-5 text-slate-500">A focused next step for your target role.</p><div className="mt-4 rounded-xl bg-slate-50 p-4"><p className="text-sm font-bold text-slate-800">Build Machine Learning fundamentals</p><p className="mt-2 text-xs leading-5 text-slate-500">This is your largest current gap and can unlock stronger project readiness.</p><span className="mt-3 inline-flex rounded-full bg-rose-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-rose-700">Highest priority</span></div></section></div>
  </div>
}

export default EmployeeCompetencyPage
