import { FiCpu } from 'react-icons/fi';
import { HiSparkles } from 'react-icons/hi';

export default function CompetencySummary({ employee }) {
  return (
    <div className="glass-card p-6 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute top-0 right-0 w-48 h-48 rounded-full bg-indigo-500/5 -translate-y-1/2 translate-x-1/2 pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-32 h-32 rounded-full bg-cyan-500/5 translate-y-1/2 -translate-x-1/2 pointer-events-none" />

      <div className="relative z-10">
        {/* Header */}
        <div className="flex items-center gap-3 mb-4">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-indigo-500/20 to-cyan-500/20 border border-indigo-500/30 flex items-center justify-center">
            <FiCpu className="text-indigo-400" size={16} />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white">AI Competency Summary</h3>
            <p className="text-xs text-slate-500 flex items-center gap-1 mt-0.5">
              <HiSparkles className="text-amber-400" size={10} />
              Generated by SkillSetu Intelligence Engine
            </p>
          </div>
          <div className="ml-auto flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/25">
            <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-pulse" />
            <span className="text-[10px] text-indigo-400 font-semibold tracking-wide">LIVE</span>
          </div>
        </div>

        {/* Divider */}
        <div className="h-px bg-gradient-to-r from-indigo-500/30 via-cyan-500/20 to-transparent mb-4" />

        {/* Summary text */}
        <blockquote className="relative">
          <span className="absolute -top-2 -left-1 text-4xl text-indigo-500/30 font-serif leading-none">"</span>
          <p className="text-slate-300 leading-relaxed text-sm pl-5 pr-2 italic">
            {employee.summary}
          </p>
          <span className="absolute -bottom-4 right-2 text-4xl text-indigo-500/30 font-serif leading-none">"</span>
        </blockquote>

        {/* Stats row */}
        <div className="mt-6 pt-4 border-t border-slate-800/60 flex items-center gap-6">
          <StatPill label="Overall Score" value={`${employee.overallScore}%`} color="text-indigo-300" />
          <StatPill label="Role Readiness" value={`${employee.readiness}%`} color="text-emerald-300" />
          <StatPill label="Strengths" value={employee.strengths.length} color="text-cyan-300" />
          <StatPill label="To Improve" value={employee.improvements.length} color="text-amber-300" />
        </div>
      </div>
    </div>
  );
}

function StatPill({ label, value, color }) {
  return (
    <div className="flex flex-col">
      <span className={`text-lg font-bold font-display ${color}`}>{value}</span>
      <span className="text-xs text-slate-500 font-medium">{label}</span>
    </div>
  );
}

